name: Build and publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_unoicu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        EMSCRIPTEN_VERSION: [ '3.1.12','3.1.34','3.1.56' ]
    steps:
      - uses: actions/checkout@v2

      - name: Build unoicu.a
        run: |
          pushd src/unoicu
          docker build --build-arg EMSCRIPTEN_VERSION=${{ matrix.EMSCRIPTEN_VERSION }} --output type=local,dest=./out .
          popd

      - name: Upload unoicu.a
        uses: actions/upload-artifact@v4
        with:
          name: unoicu-${{ matrix.EMSCRIPTEN_VERSION }}
          path: ./src/unoicu/out

  build_icudt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build icudt.dat
        env:
          ICU_SOURCE_ZIP_URL: https://github.com/unicode-org/icu/archive/refs/tags/release-77-1.zip
        run: |
          pushd src/cldr_data
          docker build --build-arg ICU_SOURCE_ZIP_URL=${ICU_SOURCE_ZIP_URL} --output type=local,dest=. .
          popd

      - name: Upload icudt.dat
        uses: actions/upload-artifact@v4
        with:
          name: icudt.dat
          path: ./src/cldr_data/icudt.dat

  package:
    needs: [build_unoicu, build_icudt]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: merged-artifacts
          pattern: '*'
          separate-directories: true

      - name: Download merged artifacts
        uses: actions/download-artifact@v4
        with:
          name: merged-artifacts
          path: ./merged-artifacts

      - name: List files
        run: |
          Get-ChildItem -Recurse .

      - name: Move downloaded artifacts to correct locations
        shell: bash
        run: |
          mv ./merged-artifacts/icudt.dat/icudt.dat ./nuget/build
          
          mkdir -p ./nuget/buildTransitive/native/unoicu.a
          pushd merged-artifacts
          for dir in unoicu-*; do
            new_name="${dir#unoicu-}"
            mkdir -p ../nuget/buildTransitive/native/unoicu.a/"$new_name"/st
            cp -r "$dir"/unoicu.a ../nuget/buildTransitive/native/unoicu.a/"$new_name"/st/unoicu.a
          done
          popd

      - name: List files
        run: |
          Get-ChildItem -Recurse .

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 8.0.100

      - name: Build nuget
        run: |
          pushd nuget
          .\nuget.exe pack uno.icu-wasm.nuspec
          popd

      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: ./nuget/*.nupkg